spring.application.name=incident-tracker-api
spring.datasource.url=jdbc:postgresql://localhost:5432/incident_tracker_api
spring.datasource.username=postgres
spring.datasource.password=mouypassword77
spring.jpa.hibernate.ddl-auto=update
